#!/bin/bash
# Project_zero skript
# Author: mlitwora@redhat.com
# zavolani bez parametru vypise aktualni cas
# parametr --version vypise presny cas a hostname kdy byl vybuildeni
#
#
#

if [ $# = "0" ]; then 
	CURRENT_TIME=$(date +"%T")
	echo "Current time: $CURRENT_TIME"
	exit 0

elif [ $# = "1" ] && [ $1 = "--version" ]; then
	echo "Hostname: localhost.localdomain "
	echo "Date of build: Tue 16 Jul 2019 12:47:32 PM CEST"
	exit 0

else
	echo "Wrong arguments" >&2
	exit 1
fi
